### ISSUE TITLE
Q: Add config file?

### ISSUE THREAD

**Issue by tlkamp** [circa10a/ouroboros#46]
We could add the option to specify a configuration file (that users could ultimately version control).

This configuration file could configure `ouroboros` itself, or it could be an inventory of containers to monitor/ignore. Or both. 
  - Maybe pick one for now and then add other config options later

Off the top of my head, we could do:
- `.json`
- `.yml` / `.yaml`
- `.ini`
- `.txt`

**Comment by circa10a** [comment]
Not a bad idea. I'm a fan of json myself since almost everything supports it.

You thinking a `--config` opt that can only run by itself? Mixing and matching other opts could get a little messy...

**Comment by circa10a** [comment]
@tlkamp Since all the config options are supported via environment variables, maybe we just add docs demonstrating use of `--env-file` with all of the config options? This would effectively add the use of a config file without an extra logic.

https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by tlkamp** [comment]
Yeah, that sounds good to me.
