### ISSUE TITLE
Update stopped containers

### ISSUE THREAD

**Issue by cmsj** [circa10a/ouroboros#60]
I have some periodic tasks that get run in short-lived containers. Rather than destroy and recreate the containers each time, they are created and just spend most of their time stopped.

How reasonable would it be for ouroboros to be able to monitor and update these containers?

**Comment by circa10a** [comment]
I think this is easily doable. How do you feel about a `--update-stopped` argument?

**Comment by cmsj** [comment]
Sounds ideal to me 👍

**Comment by circa10a** [comment]
@cmsj before I do any work on this. You're use case seems like a good opportunity for FaaS. Have you explored that at all?

**Comment by circa10a** [comment]
@cmsj 
Got some bad news. I dug into the [docker sdk](https://docker-py.readthedocs.io/en/stable/api.html#containers) a little deeper and the api only accepts one status string (running, exited, paused, restarting). So ouroboros will not be able to monitor stopped containers as is.

You can see the details in the docs linked above under the `containers` section then` filter` parameter.

There are still a couple of options though:

1. Open feature request for [docker-py](https://github.com/docker/docker-py). I don't think it would be added anytime soon thought since there is only 1 guy maintaining the project.

2. Fork ouroboros and [change the status filter](https://github.com/circa10a/ouroboros/blob/master/ouroboros/container.py#L25) to monitor `exited` containers. You would need 2 ouroboros instances to monitor running and exited containers. Depends on what you need. If you're only trying to update your short lived stopped containers. You only need the one modified instance.

Sucks I know, but I'm currently limited to what docker-py supports.
